Algoritmo "Divisão"
//Disciplina  : [Lógica de Programação no visual g]
// Professor   : Jailson Costa dos Santos
// Descrição   : receber o nome do usuário e exibir com a mensagem de seja bem vindo com o nome
// Autor(a)    : Guilherme Machado da Silva
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
numero01:inteiro
numero02:inteiro
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite um numero :")
 leia(numero01)
 escreva("Digite outro numero :")
 leia(numero02)
 resultado<- numero01 / numero02
 escreva("o resultado da sua divisão é :", resultado)

Fimalgoritmo