Algoritmo "ExemploPara"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Machado da Silva
// Data atual  : 14/04/2026
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Exemplo de laço para")
   para contadora de 1 ate 10 passo 1 faca
      escreval(contadora)
   fimpara

Fimalgoritmo