Algoritmo "perimetroDoQuadrado"
// Disciplina  : [ Lógica de Programação com visual g ]
// Professor   : Jailson Costa dos Santos 
// Descrição   : solicita os valores do lado do quadrado e multiplica
// Autor(a)    : Guilherme Machado da Silva
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
lado:real
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o valor do lado do quadrado")
leia(lado)
resultado<- lado*4
escreval("O valor do perimetro do quadrado é ",resultado)

Fimalgoritmo