Algoritmo "semnome"
// Disciplina   : [ Lógica de Programação com visual g ]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis 
contadora:inteiro
somar:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto contadora <100 faça
contadora<- contadora+1
somar <- somar + contadora
fimenquanto
escreval("A soma de todos os numeros naturais até 100 são :",somar)

Fimalgoritmo