Algoritmo "somadetermosecalculodeproduto"
// Disciplina   : [ Lógica de Programação com visual g ]
// Professor   : Jailson Costa dos Santos 
// Descrição   :Calcula o produto de A e C, e a soma de B e D
// Autor(a)    : Guilherme Machado
// Data atual  : 17/04/2026
var
   A, B, C, D, P, S: Inteiro

inicio
   Escreva("Digite o valor A: ")
   Leia(A)
   Escreva("Digite o valor B: ")
   Leia(B)
   Escreva("Digite o valor C: ")
   Leia(C)
   Escreva("Digite o valor D: ")
   Leia(D)

   P <- A * C
   S <- B + D

   Escreval("Resultado do produto (A * C): ", P)
   Escreval("Resultado da soma (B + D): ", S)
   Fimalgoritmo