Algoritmo "Àrea do triangulo"
//Disciplina  : [Lógica de Programação no visual g]
// Professor   : Jailson Costa dos Santos
// Descrição   : realizar o procedimento para descobrir a area do poligono
// Autor(a)    : Guilherme Machado da Silva
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
numero01:inteiro
numero02:inteiro
resultado:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 escreva("Digite a base do triangulo :")
 leia(numero01)
 escreva("Digite a altura do triangulo :")
 leia(numero02)
 resultado<- numero01 * numero02 / 2
 escreva("A area do seu quadrado é :", resultado)

Fimalgoritmo